[package]
name = "loopers-engine"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = "0.2"
crossbeam-channel = "0.4"
rand = "0.6"
hound = "3.4.0"
chrono = "0.4.11"
lazy_static = "1.4.0"
bytes = "0.4"
prost = "0.5"

tokio = "0.1"
tower-request-modifier = { git = "https://github.com/tower-rs/tower-http" }
tower-hyper = { git = "https://github.com/tower-rs/tower-hyper" }
hyper = "0.12"
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc", features = ["tower-hyper"] }
tower-service = "0.2"
tower-util = "0.1"

futures = "0.1"

dirs = "2"

log = "0.4"

loopers-common = { path = "../loopers-common" }

[dev-dependencies]
tempfile = "3.1.0"
fern = "0.6"
criterion = "0.3"

[[bench]]
name = "looper_benchmarks"
harness = false
