[package]
name = "loopers"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
jack = "0.6"
crossbeam-queue = "0.1"
crossbeam-channel = "0.3"
rand = "0.6"
tui = "0.5"
termion = "1.5"
log = "0.4"
log4rs = "0.8"
