[package]
name = "loopers-common"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }

csv = "1.1"

crossbeam-queue = "0.2"
crossbeam-channel = "0.4"
arrayvec = "0.5.1"

log = "0.4"

tempfile = "3"

derive_more = "0.99"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
