[package]
name = "loopers-common"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
prost = "0.5"
bytes = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }

csv = "1.1"

crossbeam-queue = "0.2"
crossbeam-channel = "0.4"

log = "0.4"

[build-dependencies]
prost-build = "0.5"
serde = { version = "1.0", features = ["derive"] }
