[package]
name = "loopers-gui"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
hound = "3.4.0"

bytes = "0.5"
prost = "0.6"

skia-safe = {version = "0.29", features = ["gl"]}

glutin = "0.24"
gl-rs = { package = "gl", version = "0.14.0" }

[build-dependencies]
prost-build = "0.6"
