[package]
name = "loopers-gui"
version = "0.1.0"
authors = ["Micah Wylde <micah@micahw.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
hound = "3.4.0"

bytes = "0.5"
dirs = "1.0"

skia-safe = {version = "0.29", features = ["gl"]}

glutin = "0.24"
winit = "0.22"
tinyfiledialogs = "3.3"
lazy_static = "1"

gl-rs = { package = "gl", version = "0.14.0" }
crossbeam-queue = "0.2"
crossbeam-channel = "0.4"

loopers-common = { path = "../loopers-common" }
