name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libjack-dev
    - name: Build
      run: cargo build -v --features=fail-on-warnings
    - name: Run tests
      run: cargo test --verbose
