name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libjack-dev libgl1-mesa-dev libsdl2-dev
    - name: Build
      run: cargo build -v
    - name: Run tests
      run: cargo test --verbose
